--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: redis
  name: redis
  namespace: vote
spec: 
  clusterIP: None
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector: 
    app: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: vote
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
          name: redis

--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: db
  name: db
  namespace: vote
spec: 
  clusterIP: None
  ports: 
    - 
      name: db
      port: 5432
      targetPort: 5432
  selector: 
    app: db



---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: vote
  name: postgres-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
      
---


apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: vote
  name: db
  # labels:
  #   app: db
spec:
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: postgres:9.4
          name: db          
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: db
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: postgres-pv-claim




---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: vote
  name: result
  labels:
    app: result
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: tarasrudko/result
        ports:
        - containerPort: 80
          name: result

---
apiVersion: v1
kind: Service
metadata:
  namespace: vote
  name: vote
  labels:
    apps: vote
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 80
      name: vote
  selector:
    app: vote
  # clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vote
  namespace: vote
  labels:
    app: vote
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: tarasrudko/vote
          ports:
            - 
              containerPort: 80
              name: vote
              
--- 
apiVersion: v1
kind: Service
metadata: 
  namespace: vote
  labels: 
    apps: worker
  name: worker
spec: 
  clusterIP: None
  selector: 
    app: worker
--- 
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  namespace: vote
  labels: 
    app: worker
  name: worker
spec: 
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: worker
    spec: 
      containers: 
        - 
          image: tarasrudko/worker
          name: worker
